version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tyrus-standalone-client"
        versions: [ "2.x" ]
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "tyrus-standalone-client"
        versions: [ "2.x" ]
    groups:
      bolt-maven:
        patterns:
          - "bolt*"
